# Sklearn Score Samples

Stupid bonsai does not do classification. Fuck that shit.

## Imports

In [1]:
# Basic imports
import sklearn
import numpy as np
import pandas as pd
import os
import sys


from os.path import dirname
from sklearn.tree import *
from sklearn.datasets import load_iris,load_boston
from sklearn.metrics import f1_score, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [2]:
note_dir = os.getcwd()
root_dir = dirname(note_dir)
src_dir = os.path.join(root_dir, 'src')

sys.path.extend([src_dir])

In [3]:
import palmbomen

## Dataset

In [4]:
iris = load_iris()
X, y = iris['data'], iris['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
train = pd.DataFrame(X_train)
train = train.assign(y=y_train)
np.random.shuffle(y_train)
train = train.assign(y2=y_train)
train.head()

0    1    2    3  y  y2
0  5.8  2.7  4.1  1.0  1   1
1  6.3  3.3  4.7  1.6  1   1
2  5.1  3.4  1.5  0.2  0   1
3  6.7  3.3  5.7  2.5  2   0
4  6.0  2.2  5.0  1.5  2   1

In [6]:
test = pd.DataFrame(X_test)
test = test.assign(y=y_test)
np.random.shuffle(y_test)
test = test.assign(y2=y_test)
test.head()

0    1    2    3  y  y2
0  5.5  3.5  1.3  0.2  0   2
1  5.0  3.5  1.6  0.6  0   2
2  5.1  3.8  1.6  0.2  0   0
3  6.2  2.9  4.3  1.3  1   0
4  5.4  3.4  1.5  0.4  0   1

In [7]:
X_train, y_train = train.values[:, :-3], train.values[:, -2:].astype(int)
X_test, y_test = test.values[:, :-3], test.values[:, -2:].astype(int)

In [8]:
y_test.shape

(30, 2)

## Palmboom 01

Ok its not so orderly anymore, but almost up and running now.

In [9]:
cboom = palmbomen.PalmboomClassifier(max_depth=3)

In [10]:
cboom.fit(X_train, y_train)

PalmboomClassifier()

In [11]:
cboom.predict_proba(X_test[:5])

[array([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [1., 0., 0.]]), array([[0.22580645, 0.41935484, 0.35483871],
        [0.22580645, 0.41935484, 0.35483871],
        [0.22580645, 0.41935484, 0.35483871],
        [0.4137931 , 0.4137931 , 0.17241379],
        [0.22580645, 0.41935484, 0.35483871]])]

In [12]:
cboom.score_samples(X_test[:5], y_test[:5])

array([[1.        , 0.35483871],
       [1.        , 0.35483871],
       [1.        , 0.22580645],
       [1.        , 0.4137931 ],
       [1.        , 0.41935484]])

In [13]:
y_test[:5]

array([[0, 2],
       [0, 2],
       [0, 0],
       [1, 0],
       [0, 1]])

# Sandbox

In [14]:
max_depth = 2
estimator = DecisionTreeClassifier(max_depth=max_depth)

In [15]:
estimator.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [16]:
n_nodes = estimator.tree_.node_count
children_left = estimator.tree_.children_left
children_right = estimator.tree_.children_right
feature = estimator.tree_.feature
threshold = estimator.tree_.threshold

In [17]:
n_nodes

7

It is pretty easy to get the paths reached by each sample through the tree

In [18]:
node_indicator = estimator.decision_path(X_test)

And also to get the leaf ID

In [19]:
leaf_ids = estimator.apply(X_test)
for x in leaf_ids[:10]:
    print(estimator.tree_.value[x])

[[33.  0.  0.]
 [ 7. 13. 13.]]
[[33.  0.  0.]
 [ 7. 13. 13.]]
[[33.  0.  0.]
 [ 7. 13. 13.]]
[[ 0. 36.  0.]
 [12. 15.  9.]]
[[33.  0.  0.]
 [ 7. 13. 13.]]
[[33.  0.  0.]
 [ 7. 13. 13.]]
[[ 0.  6. 43.]
 [14. 14. 21.]]
[[33.  0.  0.]
 [ 7. 13. 13.]]
[[33.  0.  0.]
 [ 7. 13. 13.]]
[[ 0. 36.  0.]
 [12. 15.  9.]]


In [20]:
estimator.predict_proba(X_test)

[array([[1.        , 0.        , 0.        ],
        [1.        , 0.        , 0.        ],
        [1.        , 0.        , 0.        ],
        [0.        , 1.        , 0.        ],
        [1.        , 0.        , 0.        ],
        [1.        , 0.        , 0.        ],
        [0.        , 0.12244898, 0.87755102],
        [1.        , 0.        , 0.        ],
        [1.        , 0.        , 0.        ],
        [0.        , 1.        , 0.        ],
        [1.        , 0.        , 0.        ],
        [1.        , 0.        , 0.        ],
        [0.        , 0.12244898, 0.87755102],
        [0.        , 0.12244898, 0.87755102],
        [1.        , 0.        , 0.        ],
        [1.        , 0.        , 0.        ],
        [0.        , 1.        , 0.        ],
        [0.        , 1.        , 0.        ],
        [0.        , 1.        , 0.        ],
        [0.        , 0.12244898, 0.87755102],
        [0.        , 0.12244898, 0.87755102],
        [0.        , 1.        , 0

## Regression

In [21]:
boston = load_boston()
X, y = boston['data'], boston['target']

data = pd.DataFrame(X)
data = data.assign(y1=y)
np.random.shuffle(y)
data = data.assign(y2=y)
data.head()

0     1     2    3      4      5     6       7    8      9    10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12    y1    y2  
0  396.90  4.98  24.0  15.4  
1  396.90  9.14  21.6  24.0  
2  392.83  4.03  34.7  11.8  
3  394.63  2.94  33.4  24.3  
4  396.90  5.33  36.2  15.6

In [22]:
X_train, X_test, y_train, y_test = train_test_split(data.values[:, :-2], data.values[:, -2:], test_size=0.2)

In [23]:
max_depth = 5
estimator = DecisionTreeRegressor(max_depth=max_depth)

In [24]:
estimator.fit(X_train, y_train)


DecisionTreeRegressor(criterion='mse', max_depth=5, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [25]:
leaf_ids = estimator.apply(X_test)

In [26]:
leaf_ids
for x in leaf_ids[:10]:
    print(estimator.tree_.value[x])

[[18.35294118]
 [17.32941176]]
[[15. ]
 [26.6]]
[[11.775]
 [22.34 ]]
[[21.15333333]
 [24.6       ]]
[[21.15333333]
 [24.6       ]]
[[21.15333333]
 [24.6       ]]
[[21.15333333]
 [24.6       ]]
[[18.35294118]
 [17.32941176]]
[[10.9]
 [50. ]]
[[21.1 ]
 [19.54]]


In [27]:
estimator.predict(X_test)[:10]

array([[18.35294118, 17.32941176],
       [15.        , 26.6       ],
       [11.775     , 22.34      ],
       [21.15333333, 24.6       ],
       [21.15333333, 24.6       ],
       [21.15333333, 24.6       ],
       [21.15333333, 24.6       ],
       [18.35294118, 17.32941176],
       [10.9       , 50.        ],
       [21.1       , 19.54      ]])

In [28]:
def build_contents_leaf(estimator, X, y):
    """
    Useful datastructure for learning the kdes.
    """
    y = np.atleast_2d(y).T
    n, m = y.shape

    contents_leaf = np.zeros((n, m + 1))
    contents_leaf[:, :m] = y[:, :]                                  # First m columns are ground truth contents
    contents_leaf[:, -1] = estimator.apply(X)                       # Last column is leaf index
    return contents_leaf

In [29]:
from scipy.special import expit
from sklearn.neighbors import KernelDensity

In [30]:
def get_kdes(tree, X, y, **kwargs):

    contents_leaf = build_contents_leaf(tree, X, y)

    def scotts_factor(a):
        n, m = a.shape

        h = n ** (-1.0 / (m + 4))
        return h

    leaves = np.unique(contents_leaf[:, -1])
    kdes = {leaf_idx: None for leaf_idx in leaves}

    for leaf_idx in leaves:
        leaf_mask = contents_leaf[:, -1] == leaf_idx
        leaf_data = contents_leaf[leaf_mask, :-1]

        # Dynamical bandwidth selection
        bandwidth = scotts_factor(leaf_data)

        kdes[leaf_idx] = KernelDensity(bandwidth=bandwidth, **kwargs).fit(leaf_data)

    tree.kdes = kdes
    return

In [31]:
def score_samples(tree, X, y):

    n, m = X.shape
    out = np.zeros(n, dtype=np.float)

    leaf_idxs = tree.apply(X)

    u_leaf_idxs = np.unique(leaf_idxs).astype(int)

    for leaf_idx in u_leaf_idxs:
        leaf_mask = leaf_idxs == leaf_idx
        leaf_data = np.atleast_2d(y[leaf_mask]).T
        out[leaf_mask] = tree.kdes[leaf_idx].score_samples(leaf_data)

    return np.exp(out)

In [32]:
import palmbomen

In [33]:
dir(palmbomen)

['PalmboomClassifier',
 'PalmboomRegressor',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'core']

### Palmboom Single Target Regression

In [34]:
rboom_st = palmbomen.PalmboomRegressor(max_depth=2)
rboom_st.fit(X_train, y_train[:, :-1], marginal_kdes=True, joint_kdes=True)

Training Data Dimension: (197, 1)
Training Data Dimension: (141, 1)
Training Data Dimension: (39, 1)
Training Data Dimension: (27, 1)


In [35]:
msg = """
Training Data Dimension: {}
Test Data Dimension:     {}
""".format(y_train[:, :-1].shape, y_test[:, :-1].shape)
print(msg)


Training Data Dimension: (404, 1)
Test Data Dimension:     (102, 1)



In [36]:
probas = rboom_st.marginal_score_samples(X_test, y_test[:, :-1])
probas[:10]*100

array([3.50963882e+00, 2.72434879e-20, 9.66409521e+00, 1.16270283e+01,
       9.21167412e+00, 1.12455267e+01, 6.23344125e+00, 9.01536795e+00,
       4.48400151e+00, 9.54667067e+00])

In [37]:
probas = rboom_st.joint_score_samples(X_test, y_test[:, :-1])
probas[:10]*100

Test Data Dimension: (57, 1)
Test Data Dimension: (34, 1)
Test Data Dimension: (8, 1)
Test Data Dimension: (3, 1)


array([3.50963882e+00, 2.72434879e-20, 9.66409521e+00, 1.16270283e+01,
       9.21167412e+00, 1.12455267e+01, 6.23344125e+00, 9.01536795e+00,
       4.48400151e+00, 9.54667067e+00])

So, as we can see in the single target case there is no difference between joint and marginal.

### Palmboom Multi-Target Regression

In [38]:
rboom_mt = palmbomen.PalmboomRegressor(max_depth=2)
rboom_mt.fit(X_train, y_train, marginal_kdes=True, joint_kdes=True)

Training Data Dimension: (197, 2)
Training Data Dimension: (141, 2)
Training Data Dimension: (39, 2)
Training Data Dimension: (27, 2)


In [39]:
msg = """
Training Data Dimension: {}
Test Data Dimension:     {}
""".format(y_train.shape, y_test.shape)
print(msg)


Training Data Dimension: (404, 2)
Test Data Dimension:     (102, 2)



In [40]:
probas = rboom_mt.marginal_score_samples(X_test, y_test)
probas[:10]*100

array([[3.50963882e+00, 3.13993611e+00],
       [2.72434879e-20, 1.80741970e+00],
       [9.66409521e+00, 7.75207638e+00],
       [1.16270283e+01, 5.10227332e+00],
       [9.21167412e+00, 6.72849230e+00],
       [1.12455267e+01, 3.93818624e+00],
       [6.23344125e+00, 6.56992351e+00],
       [9.01536795e+00, 7.46250924e+00],
       [4.48400151e+00, 2.24306808e+00],
       [9.54667067e+00, 8.09427124e+00]])

In [41]:
res = probas[:, 0] * probas[:, 1]
res[:10]*10000

array([1.10200417e+01, 4.92404167e-20, 7.49168042e+01, 5.93242764e+01,
       6.19806784e+01, 4.42869786e+01, 4.09532322e+01, 6.72772667e+01,
       1.00579207e+01, 7.72733418e+01])

In [42]:
probas = rboom_mt.joint_score_samples(X_test, y_test)
probas[:10]*100

Test Data Dimension: (57, 2)
Test Data Dimension: (34, 2)
Test Data Dimension: (8, 2)
Test Data Dimension: (3, 2)


array([7.39827418e-02, 4.19966446e-47, 1.09532626e+00, 4.54262846e-01,
       4.42203904e-01, 2.55657049e-01, 8.91784699e-02, 2.64423260e-01,
       2.36900386e-06, 4.54206836e-01])

In [43]:
{x for x in range(3)}

{0, 1, 2}

In [47]:
rboom_mt.get_params(deep=False)

{}

In [48]:
m_codes = np.array([[1,0,0],[0,1,0]])
m_codes

array([[1, 0, 0],
       [0, 1, 0]])

In [53]:
np.atleast_2d(m_codes[0, :]).shape

(1, 3)