# Sklearn Score Samples

Stupid bonsai does not do classification. Fuck that shit.

## Imports

In [1]:
# Basic imports
import sklearn
import numpy as np
import pandas as pd
import os
import sys


from os.path import dirname
from sklearn.tree import *
from sklearn.datasets import load_iris,load_boston
from sklearn.metrics import f1_score, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [2]:
note_dir = os.getcwd()
root_dir = dirname(note_dir)
src_dir = os.path.join(root_dir, 'src')

sys.path.extend([src_dir])

In [3]:
import palmbomen

## Dataset

In [4]:
iris = load_iris()
X, y = iris['data'], iris['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
train = pd.DataFrame(X_train)
train = train.assign(y=y_train)
np.random.shuffle(y_train)
train = train.assign(y2=y_train)
train.head()

0    1    2    3  y  y2
0  5.4  3.0  4.5  1.5  1   2
1  5.8  2.6  4.0  1.2  1   1
2  6.9  3.1  5.4  2.1  2   1
3  5.0  3.4  1.6  0.4  0   1
4  5.7  3.0  4.2  1.2  1   1

In [6]:
test = pd.DataFrame(X_test)
test = test.assign(y=y_test)
np.random.shuffle(y_test)
test = test.assign(y2=y_test)
test.head()

0    1    2    3  y  y2
0  6.0  3.4  4.5  1.6  1   2
1  6.7  3.3  5.7  2.5  2   2
2  4.9  3.1  1.5  0.2  0   2
3  5.0  2.3  3.3  1.0  1   0
4  6.3  2.5  4.9  1.5  1   0

In [7]:
X_train, y_train = train.values[:, :-3], train.values[:, -2:].astype(int)
X_test, y_test = test.values[:, :-3], test.values[:, -2:].astype(int)

In [8]:
y_test.shape

(30, 2)

## Palmboom 01

Ok its not so orderly anymore, but almost up and running now.

In [9]:
cboom = palmbomen.PalmboomClassifier(max_depth=3)

In [10]:
cboom.fit(X_train, y_train)

PalmboomClassifier()

In [11]:
cboom.predict_proba(X_test[:5])

[array([[0.    , 0.875 , 0.125 ],
        [0.    , 0.0625, 0.9375],
        [1.    , 0.    , 0.    ],
        [0.    , 1.    , 0.    ],
        [0.    , 0.    , 1.    ]]),
 array([[0.375     , 0.125     , 0.5       ],
        [0.25      , 0.5625    , 0.1875    ],
        [0.16129032, 0.4516129 , 0.38709677],
        [0.32      , 0.44      , 0.24      ],
        [0.47826087, 0.17391304, 0.34782609]])]

In [12]:
cboom.score_samples(X_test[:5], y_test[:5])

array([[0.875     , 0.5       ],
       [0.9375    , 0.1875    ],
       [1.        , 0.38709677],
       [1.        , 0.32      ],
       [0.        , 0.47826087]])

In [13]:
y_test[:5]

array([[1, 2],
       [2, 2],
       [0, 2],
       [1, 0],
       [1, 0]])

# Sandbox

In [14]:
max_depth = 2
estimator = DecisionTreeClassifier(max_depth=max_depth)

In [15]:
estimator.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [16]:
n_nodes = estimator.tree_.node_count
children_left = estimator.tree_.children_left
children_right = estimator.tree_.children_right
feature = estimator.tree_.feature
threshold = estimator.tree_.threshold

In [17]:
n_nodes

7

It is pretty easy to get the paths reached by each sample through the tree

In [18]:
node_indicator = estimator.decision_path(X_test)

And also to get the leaf ID

In [19]:
leaf_ids = estimator.apply(X_test)
for x in leaf_ids[:10]:
    print(estimator.tree_.value[x])

[[ 0. 39.  2.]
 [14. 13. 14.]]
[[ 0.  1. 38.]
 [15. 13. 11.]]
[[33.  0.  0.]
 [ 7. 14. 12.]]
[[ 0. 39.  2.]
 [14. 13. 14.]]
[[ 0.  1. 38.]
 [15. 13. 11.]]
[[ 0.  1. 38.]
 [15. 13. 11.]]
[[ 0.  1. 38.]
 [15. 13. 11.]]
[[ 0.  1. 38.]
 [15. 13. 11.]]
[[ 0.  1. 38.]
 [15. 13. 11.]]
[[ 0.  1. 38.]
 [15. 13. 11.]]


In [20]:
estimator.predict_proba(X_test)

[array([[0.        , 0.95121951, 0.04878049],
        [0.        , 0.02564103, 0.97435897],
        [1.        , 0.        , 0.        ],
        [0.        , 0.95121951, 0.04878049],
        [0.        , 0.02564103, 0.97435897],
        [0.        , 0.02564103, 0.97435897],
        [0.        , 0.02564103, 0.97435897],
        [0.        , 0.02564103, 0.97435897],
        [0.        , 0.02564103, 0.97435897],
        [0.        , 0.02564103, 0.97435897],
        [1.        , 0.        , 0.        ],
        [1.        , 0.        , 0.        ],
        [0.        , 0.02564103, 0.97435897],
        [0.        , 0.02564103, 0.97435897],
        [0.        , 0.02564103, 0.97435897],
        [0.        , 0.95121951, 0.04878049],
        [0.        , 0.95121951, 0.04878049],
        [1.        , 0.        , 0.        ],
        [1.        , 0.        , 0.        ],
        [0.        , 0.95121951, 0.04878049],
        [0.        , 0.02564103, 0.97435897],
        [1.        , 0.        , 0

## Regression

In [21]:
boston = load_boston()
X, y = boston['data'], boston['target']

data = pd.DataFrame(X)
data = data.assign(y1=y)
np.random.shuffle(y)
data = data.assign(y2=y)
data.head()

0     1     2    3      4      5     6       7    8      9    10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12    y1    y2  
0  396.90  4.98  24.0  26.6  
1  396.90  9.14  21.6  15.6  
2  392.83  4.03  34.7  32.2  
3  394.63  2.94  33.4  14.8  
4  396.90  5.33  36.2  13.3

In [22]:
X_train, X_test, y_train, y_test = train_test_split(data.values[:, :-2], data.values[:, -2:], test_size=0.2)

In [23]:
max_depth = 5
estimator = DecisionTreeRegressor(max_depth=max_depth)

In [24]:
estimator.fit(X_train, y_train)


DecisionTreeRegressor(criterion='mse', max_depth=5, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [25]:
leaf_ids = estimator.apply(X_test)

In [26]:
leaf_ids
for x in leaf_ids[:10]:
    print(estimator.tree_.value[x])

[[32.49512195]
 [21.68536585]]
[[20.717]
 [22.489]]
[[17.03636364]
 [20.34      ]]
[[43.1]
 [ 8.5]]
[[32.49512195]
 [21.68536585]]
[[24.37159091]
 [21.44886364]]
[[24.37159091]
 [21.44886364]]
[[20.717]
 [22.489]]
[[11.83636364]
 [23.80454545]]
[[24.37159091]
 [21.44886364]]


In [27]:
estimator.predict(X_test)[:10]

array([[32.49512195, 21.68536585],
       [20.717     , 22.489     ],
       [17.03636364, 20.34      ],
       [43.1       ,  8.5       ],
       [32.49512195, 21.68536585],
       [24.37159091, 21.44886364],
       [24.37159091, 21.44886364],
       [20.717     , 22.489     ],
       [11.83636364, 23.80454545],
       [24.37159091, 21.44886364]])

In [28]:
def build_contents_leaf(estimator, X, y):
    """
    Useful datastructure for learning the kdes.
    """
    y = np.atleast_2d(y).T
    n, m = y.shape

    contents_leaf = np.zeros((n, m + 1))
    contents_leaf[:, :m] = y[:, :]                                  # First m columns are ground truth contents
    contents_leaf[:, -1] = estimator.apply(X)                       # Last column is leaf index
    return contents_leaf

In [29]:
from scipy.special import expit
from sklearn.neighbors import KernelDensity

In [30]:
def get_kdes(tree, X, y, **kwargs):

    contents_leaf = build_contents_leaf(tree, X, y)

    def scotts_factor(a):
        n, m = a.shape

        h = n ** (-1.0 / (m + 4))
        return h

    leaves = np.unique(contents_leaf[:, -1])
    kdes = {leaf_idx: None for leaf_idx in leaves}

    for leaf_idx in leaves:
        leaf_mask = contents_leaf[:, -1] == leaf_idx
        leaf_data = contents_leaf[leaf_mask, :-1]

        # Dynamical bandwidth selection
        bandwidth = scotts_factor(leaf_data)

        kdes[leaf_idx] = KernelDensity(bandwidth=bandwidth, **kwargs).fit(leaf_data)

    tree.kdes = kdes
    return

In [31]:
def score_samples(tree, X, y):

    n, m = X.shape
    out = np.zeros(n, dtype=np.float)

    leaf_idxs = tree.apply(X)

    u_leaf_idxs = np.unique(leaf_idxs).astype(int)

    for leaf_idx in u_leaf_idxs:
        leaf_mask = leaf_idxs == leaf_idx
        leaf_data = np.atleast_2d(y[leaf_mask]).T
        out[leaf_mask] = tree.kdes[leaf_idx].score_samples(leaf_data)

    return np.exp(out)

In [32]:
import palmbomen

In [33]:
dir(palmbomen)

['PalmboomClassifier',
 'PalmboomRegressor',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'core']

### Palmboom Single Target Regression

In [44]:
rboom_st = palmbomen.PalmboomRegressor(max_depth=2)
rboom_st.fit(X_train, y_train[:, :-1], marginal_kdes=True, joint_kdes=True)

Training Data Dimension: (150, 1)
Training Data Dimension: (24, 1)
Training Data Dimension: (104, 1)
Training Data Dimension: (126, 1)


In [45]:
msg = """
Training Data Dimension: {}
Test Data Dimension:     {}
""".format(y_train[:, :-1].shape, y_test[:, :-1].shape)
print(msg)


Training Data Dimension: (404, 1)
Test Data Dimension:     (102, 1)



In [46]:
probas = rboom_st.marginal_score_samples(X_test, y_test[:, :-1])
probas[:10]*100

array([ 5.26030077, 13.91644821, 11.65150237, 25.40691212,  4.45536289,
       12.03265614, 11.26660977, 17.48674678,  9.52096515,  8.54515033])

In [48]:
probas = rboom_st.joint_score_samples(X_test, y_test[:, :-1])
probas[:10]*100

Test Data Dimension: (32, 1)
Test Data Dimension: (6, 1)
Test Data Dimension: (28, 1)
Test Data Dimension: (36, 1)


array([ 5.26030077, 13.91644821, 11.65150237, 25.40691212,  4.45536289,
       12.03265614, 11.26660977, 17.48674678,  9.52096515,  8.54515033])

So, as we can see in the single target case there is no difference between joint and marginal.

### Palmboom Multi-Target Regression

In [49]:
rboom_mt = palmbomen.PalmboomRegressor(max_depth=2)
rboom_mt.fit(X_train, y_train, marginal_kdes=True, joint_kdes=True)

Training Data Dimension: (150, 2)
Training Data Dimension: (24, 2)
Training Data Dimension: (164, 2)
Training Data Dimension: (66, 2)


In [50]:
msg = """
Training Data Dimension: {}
Test Data Dimension:     {}
""".format(y_train.shape, y_test.shape)
print(msg)


Training Data Dimension: (404, 2)
Test Data Dimension:     (102, 2)



In [61]:
probas = rboom_mt.marginal_score_samples(X_test, y_test)
probas[:10]*100

array([[ 5.26030077,  7.36277619],
       [ 9.79014086,  4.4227392 ],
       [ 3.76600575,  1.99846682],
       [25.40691212,  3.65627089],
       [ 4.45536289,  4.76414603],
       [12.03265614,  2.89800708],
       [11.26660977,  5.2889068 ],
       [15.08130152,  7.12063122],
       [ 5.50190488,  3.48605741],
       [ 8.54515033,  0.64917066]])

In [64]:
res = probas[:, 0] * probas[:, 1]
res[:10]*10000

array([ 38.73041726,  43.29923977,   7.52623755,  92.89455329,
        21.22599942,  34.87072274,  59.58804905, 107.3883865 ,
        19.17995626,   5.54726088])

In [52]:
probas = rboom_mt.joint_score_samples(X_test, y_test)
probas[:10]*100

Test Data Dimension: (32, 2)
Test Data Dimension: (6, 2)
Test Data Dimension: (48, 2)
Test Data Dimension: (16, 2)


array([0.57686607, 0.63978333, 0.03207539, 1.56251349, 0.25057273,
       0.10297683, 0.46196822, 1.93117505, 0.11783867, 0.00504431])