# Bonsai Predict Proba

I need this function also in BonsaiTrees.

## Imports

In [1]:
# Basic imports
import sklearn
import numpy as np
import pandas as pd
import os
import sys


from os.path import dirname
from sklearn.tree import *
from sklearn.datasets import load_iris
from sklearn.metrics import f1_score, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [2]:
# Custom Imports
note_dir = os.getcwd()
root_dir = dirname(note_dir)
src_dir = os.path.join(root_dir, 'src')
bonsai_dir = os.path.join(src_dir, 'bonsaidt')

sys.path.extend([src_dir, bonsai_dir])

In [3]:
import bonsai
import mercs

from bonsai.base import *
from bonsai.utils.visuals import (plot_corr,
                                  plot_summary_grid)

## Datasets

In [4]:
iris = load_iris()
X, y = iris['data'], iris['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
train = pd.DataFrame(X_train)
train = train.assign(y=y_train)
train.head()

0    1    2    3  y
0  6.3  2.7  4.9  1.8  2
1  5.0  2.3  3.3  1.0  1
2  5.1  3.4  1.5  0.2  0
3  6.6  3.0  4.4  1.4  1
4  5.0  3.4  1.5  0.2  0

In [6]:
test = pd.DataFrame(X_test)
test = test.assign(y=y_test)
test.head()

0    1    2    3  y
0  6.3  3.3  4.7  1.6  1
1  6.7  3.0  5.2  2.3  2
2  5.1  3.5  1.4  0.2  0
3  4.9  3.1  1.5  0.2  0
4  4.8  3.4  1.9  0.2  0

## Training

In [7]:
max_depth=4
bonsai = C45Tree(max_depth=max_depth)
skl = DecisionTreeClassifier(max_depth=max_depth)

In [8]:
bonsai.fit(X_train, y_train)
skl.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [9]:
skl.classes_, bonsai.classes_

(array([0, 1, 2]), array([0., 1., 2.]))

In [10]:
skl.predict_proba(X_test)[:10]

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [28]:
skl.tree_.decision_path()

TypeError: decision_path() takes exactly one argument (0 given)

In [12]:
bonsai.predict(X_test, output_type="response") 

array([1.03846154, 1.03846154, 1.03846154, 1.03846154, 1.03846154,
       1.2       , 1.03846154, 1.03846154, 1.03846154, 0.        ,
       1.03846154, 1.03846154, 1.03846154, 1.03846154, 1.03846154,
       1.03846154, 1.03846154, 1.03846154, 1.03846154, 1.03846154,
       1.03846154, 1.03846154, 1.03846154, 0.        , 1.03846154,
       1.03846154, 1.03846154, 1.03846154, 1.03846154, 1.03846154])

In [13]:
bonsai.get_counts().shape

(15, 3)

In [14]:
bonsai.leaves

[{'eqs': [{'svar': 3,
    'sval': 2.3909090909090907,
    'sidx': 112,
    'op': '<',
    'missing': 1},
   {'svar': 2, 'sval': 1.1475, 'sidx': 53, 'op': '<', 'missing': 1}],
  'i_start': 0,
  'i_end': 1,
  '_id': 'ROOT::112L::53L',
  'n_samples': 2.0,
  'y': 0.0,
  'depth': 2,
  'y_lst': [1.0087719298245614, 0.0],
  'is_leaf': True,
  'index': 0},
 {'eqs': [{'svar': 3,
    'sval': 2.3909090909090907,
    'sidx': 112,
    'op': '>=',
    'missing': 0},
   {'svar': 2,
    'sval': 5.867499999999999,
    'sidx': 85,
    'op': '>=',
    'missing': 0}],
  'i_start': 118,
  'i_end': 120,
  '_id': 'ROOT::112R::85R',
  'n_samples': 2.0,
  'y': 2.0,
  'depth': 2,
  'y_lst': [2.0, 2.0],
  'is_leaf': True,
  'index': 1},
 {'eqs': [{'svar': 3,
    'sval': 2.3909090909090907,
    'sidx': 112,
    'op': '<',
    'missing': 1},
   {'svar': 2, 'sval': 1.1475, 'sidx': 53, 'op': '>=', 'missing': 0},
   {'svar': 1,
    'sval': 2.3000000000000003,
    'sidx': 34,
    'op': '<',
    'missing': 1},
   {'sva

In [15]:
len(bonsai.leaves)

8

In [16]:
skl.tree_.max_depth

4

In [17]:
tree.classes_

NameError: name 'tree' is not defined

In [ ]:
tree.discrete_probabilities

In [ ]:
class_index_dict = {v:i for i,v in enumerate(tree.classes_)}
class_index_dict

In [ ]:
for proba in tree.discrete_probabilities:
    new_proba = np.zeros(3)
    
    print(proba)
    for t in proba:
        print(t)
        print(t[0])
        class_idx = class_index_dict[t[0]]
        new_proba[class_idx] = t[1]
    
    

In [ ]:
new_proba

# Sandbox

In [ ]:
a = np.array([0, 3, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 3, 4])
unique, counts = np.unique(a, return_counts=True)


In [ ]:
list(zip(unique, counts))